### ISSUE TITLE
Error thrown if 'temp.svg' doesn't exist in the root directory

### ISSUE THREAD

**Issue by sgraber** [evride/Skylight#4]
Updated to latest commit: https://github.com/evride/Skylight/commit/5f1597ad808079e400df54fc87e5768a9ba9dad2

C:\Users\sgraber\Downloads\Skylight-master (1)\Skylight-master>main.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\threading.py", line 868, in run
    self._target(_self._args, *_self._kwargs)
  File "C:\Users\sgraber\Downloads\Skylight-master (1)\Skylight-master\main.py",
 line 62, in sliceFile
    sliceComplete()
  File "C:\Users\sgraber\Downloads\Skylight-master (1)\Skylight-master\main.py",
 line 65, in sliceComplete
    handler.openFile('temp.svg')
  File "C:\Users\sgraber\Downloads\Skylight-master (1)\Skylight-master\PrintHand
ler.py", line 66, in openFile
    self.svg = ET.parse(filename).getroot()
  File "C:\Python34\lib\xml\etree\ElementTree.py", line 1187, in parse
    tree.parse(source, parser)
  File "C:\Python34\lib\xml\etree\ElementTree.py", line 587, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'temp.svg'

**Comment by sgraber** [comment]
With last night's commit:

C:\Users\sgraber\Downloads\Skylight-master (2)\Skylight-master>main.py
can't open file
C:/Users/sgraber/Downloads/Skylight-master (2)/Skylight-master/3DBenchy.stl 0.1
C:\Users\sgraber\Downloads\Skylight-master (2)\Skylight-master/slic3r/slic3r.exe
 C:/Users/sgraber/Downloads/Skylight-master (2)/Skylight-master/3DBenchy.stl --l
ayer-height=0.1 --export-svg --output=C:\Users\sgraber\AppData\Roaming\Skylight\
temp.svg
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\threading.py", line 868, in run
    self._target(_self._args, *_self._kwargs)
  File "C:\Users\sgraber\Downloads\Skylight-master (2)\Skylight-master\main.py",
 line 89, in sliceFile
    sliceComplete()
  File "C:\Users\sgraber\Downloads\Skylight-master (2)\Skylight-master\main.py",
 line 92, in sliceComplete
    handler.openFile(appdataDir() + 'temp.svg')
  File "C:\Users\sgraber\Downloads\Skylight-master (2)\Skylight-master\PrintHand
ler.py", line 90, in openFile
    self.svg = ET.parse(filename).getroot()
  File "C:\Python34\lib\xml\etree\ElementTree.py", line 1187, in parse
    tree.parse(source, parser)
  File "C:\Python34\lib\xml\etree\ElementTree.py", line 587, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\sgraber\App
Data\Roaming\Skylight\temp.svg'
